### ISSUE TITLE
Wisol

### ISSUE THREAD

**Issue by tcpipchip** [hardwario/lora-modem-abz#110]
I will test this week in our wisol LoraWAN modules😀

**Comment by tcpipchip** [comment]
![VirtualBox_ch_16_10_2022_10_44_18](https://user-images.githubusercontent.com/11488460/196038822-47c92490-979e-4222-a120-07fbc12923b5.png)

**Comment by tcpipchip** [comment]
got this error!
On WSL2

**Comment by janakj** [comment]
You need to initialize git submodules. Please follow the steps in the section Building of README.md.

**Comment by tcpipchip** [comment]
good morning!
Yes, i had done that but
needs key access rights
![VirtualBox_ch_16_10_2022_10_58_08](https://user-images.githubusercontent.com/11488460/196039513-94a8d61b-a09e-4048-880e-9b47f7700682.png)

**Comment by janakj** [comment]
Well, you need to be able to use Github from the VM where you are building it. If that's not the case, download the [source tarball from the most recent release](https://github.com/hardwario/lora-modem-abz/releases/download/v1.2.5/lora-modem-abz-1.2.5.tar.gz) and try to build that. The source tarball does not require working git/Github.

**Comment by tcpipchip** [comment]
Now compiles! thanks!
Now i will start to convert to WISOL Module hardware!
It´s uses the STM32L071+SX1276
![image](https://user-images.githubusercontent.com/11488460/196040976-8ac901ee-6f4c-4239-a98e-66584452c01b.png)

**Comment by tcpipchip** [comment]
some tip to choose the target
STM32L072 during compile ?

**Comment by janakj** [comment]
No idea. I am not familiar with that module. Also, you will need find out how the SX1276 chip is mapped on the GPIOs on the host MCU. This firmware only supports the mapping used by Murata Type ABZ. If your module uses a different GPIO mapping, you may need to modify the source code.

**Comment by tcpipchip** [comment]
No problem! I will do! I was using the sdk at commands of stm on wisol. But looks that your is very better documented

**Comment by tcpipchip** [comment]
> This firmware only supports the mapping used by Murata Type ABZ.

Only tell me where is the file mapping…

**Comment by janakj** [comment]
src/main.c and src/sx1276-board.c.

I am going to close this issue since this is not a problem with the firmware. You are welcome to start a new discussion in the Discussions tab instead.

**Comment by tcpipchip** [comment]
Thank you

**Comment by tcpipchip** [comment]
one suggestion is to make clear where is the NSS of SX1276 in the list files
