### ISSUE TITLE
lom204

### ISSUE THREAD

**Issue by tcpipchip** [hardwario/lora-modem-abz#111]
I got this message in wisol module
![image](https://user-images.githubusercontent.com/11488460/196227457-bcdc032c-3d11-4765-95aa-87fb6dd5aaf8.png)
is it a progress ?

**Comment by janakj** [comment]
Yes, that's progress. This event indicates that the module booted
correctly. You should be able to issue AT commands to it now.

**Comment by tcpipchip** [comment]
yeah, i hope soon test  it if all going well we can include lom204 in the board list, right ? 
and i intend a blog :)

**Comment by janakj** [comment]
Yes, we can include it in the list of supported boards if it works. Do you
have the datasheet or schematic for that board?

**Comment by janakj** [comment]
Please use the Discussions tab for general questions like this. I would like to use Issues only for reporting bugs and problems with the software itself.
