### ISSUE TITLE
Link check requests are being retransmitted

### ISSUE THREAD

**Issue by jefrin-altrosyn** [hardwario/lora-modem-abz#115]
I am working on handling the behaviour of the abz module in the mkrwan 1310 board for cases where the device is not properly connected to the network due to issues like gateway down, out of range etc.

I made the device join the lora network and turned off the gateway after it sent few uplinks. When I send an link check command it fails but it is retransmitting the link check requests about 8 times. In the wiki [here](https://github.com/hardwario/lora-modem-abz/wiki/AT-Command-Interface#atlncheck) it is mentioned that the link check requests are not retransmitted and will be sent only once per request. 

![Screenshot_20221026_115918](https://user-images.githubusercontent.com/83201502/197951380-4a5f17f7-c6ca-4080-9604-1e73c4e7ed4b.png)

![Screenshot_20221026_142946](https://user-images.githubusercontent.com/83201502/197984158-1e13609d-40c4-4d16-aaa8-0ed3a58f4ecd.png)

1. Is this link check behaviour normal or did I misunderstood something?
  
2. This is not related to the above issue but do you have any idea on how often should (or when) the modem be made to re join the network?

**Comment by janakj** [comment]
Thank you for the report! Link check requests transmitted without application payload should not be retransmitted indeed. From your logs it seems that I made a mistake here. The modem should ignore the AT+REP value in this case which does not appear to be the case. I will check this.

It's hard to say how often the modem should rejoin in general. That depends on many factors, e.g., physical parameters of your network, the number of devices, intended application, security requirements, etc. The main benefit of rejoining periodically is that your session keys get reset. That limits the total number of bytes encrypted with the same session key which is good from a security perspective.

On the other hand, it may be difficult to execute a Join automatically and reliably by devices deployed in the field. An OTAA Join is a fairly disruptive operation from the device perspective. It resets many MAC parameters, including the parameters negotiated with ADR. In addition, this implementation transmits OTAA Joins with DR0 by default (for reliability), which can drain the battery if performed too often.

**Comment by janakj** [comment]
Hi @jefrin-altrosyn, I am not able to reproduce the link check retransmissions. Are you still able to reproduce the behavior? Also, what values do you have in `AT+REP` and `AT+RTYNUM`?
