### ISSUE TITLE
Feature request - add put/get command to store data in NVM

### ISSUE THREAD

**Issue by disk91** [hardwario/lora-modem-abz#116]
Could you add AT+NVM=a,0xVV and AT+NVM?a where a is an address (0 to 16 or 32) and VV is a 8b hex value. 

This command will allow to store and read data in the murata NVM space. One of the use is to store a modem setting state and some extra information. 

It is usefull when the nvm capabilities of a board is limited (like mkr1310 - even if it is supposed to have an onboarded spi flash)

**Comment by janakj** [comment]
I would be happy to consider a pull request if you want to submit one. The command should use the `AT$` prefix (`AT+` is reserved for Murata-compatible commands).

**Comment by disk91** [comment]
Unfortunately have so many projects pending :(
I will see if I found some time for doing it

**Comment by janakj** [comment]
Please feel free to start a new discussion in the Discussions tab if you start working on it and need advice.

**Comment by disk91** [comment]
Having some train today and setup the environment, will see if I can quickly made an addition for this

**Comment by disk91** [comment]
I'm close to a working version.
the current limit is the EEPROM available size, I can have a maximum of 4 byte of user data.
The code is only using 3KB on the 6KB available and I assume most of the partitions are over-estimated.
do you think @janakj we can reduce some of the partitions to extend the User NVM space ?

**Comment by disk91** [comment]
merge request sent

**Comment by janakj** [comment]
> I'm close to a working version. the current limit is the EEPROM available size, I can have a maximum of 4 byte of user data. The code is only using 3KB on the 6KB available and I assume most of the partitions are over-estimated. do you think @janakj we can reduce some of the partitions to extend the User NVM space ?

Existing partitions are left slightly larger than necessary to accommodate for future additions. Also, the size of some of LoRaMac-node data structures stored in NVM changes depending on what features and regions are enabled at compile time.  I sized the existing partitions to almost entirely fill one EEPROM bank (half total EEPROM size). But we can definitely carve out more space for the user data partition. There should be plenty of space.

I will see what can be resized when I get around to reviewing your pull request.
