### ISSUE TITLE
Device hang after JOIN

### ISSUE THREAD

**Issue by jpmeijers** [hardwario/lora-modem-abz#78]
v1.1.1 debug
> +OK=v1.1.1,2022-May-31 15:06:41 EDT,v4.6.0-20-g0e4d8127,1.1.1,1.0.4,1.0.4,RP002-1.0.1,AS923 AU915 CN470 CN779 EU433 EU868 IN865 KR920 RU864 US915␍␊

Device is registered on TTN and all keys match. When I do `AT+JOIN` or `AT+JOIN=1` I can see the join request and accept on TTN. The device stops responding to AT commands until I perform a power cycle or reset. I never get the URC over the UART.

I've tried the Murata firmware image just before this and that worked.

Board: B-L072Z-LRWAN1 dev kit.

![image](https://user-images.githubusercontent.com/948278/173383865-00ec8e61-8407-482b-9085-2987f5ab9f52.png)

```
> AT+JOIN=1␍␊
[16:54:55:139] +OK␍␊
[16:54:55:144] ␍␊
```

**Comment by jpmeijers** [comment]
I actually checked out the master branch, and did a `make release` build. That has the same behaviour.

`+OK=v1.1.1-22-g394819cd,2022-Jun-13 17:33:21 SAST,v4.6.0-20-g0e4d8127,1.1.1,1.0.4,1.0.4,RP002-1.0.1,AS923 AU915 CN470 CN779 EU433 EU868 IN865 KR920 RU864 US915␍␊`

![image](https://user-images.githubusercontent.com/948278/173411298-31fec48e-1b2b-431e-9cd6-5c33ac50d431.png)

**Comment by janakj** [comment]
I was able to reproduce the problem and fixed it on the master branch just now. Could you, please, pull from Github and try again?

I have inadvertently introduced this problem in one of the most recent commits while I was trying to optimize power consumption during sleep. The lock up that you were experiencing with the master branch version was actually unrelated to the lockup in the debug build of 1.1.1. Anyway, thanks for the report!

**Comment by jpmeijers** [comment]
Yes, current master seems to work as expected. Thanks for the quick fix.
